### ISSUE TITLE
A version of your app is using a deprecated version of Go. Please upgrade before October 1, 2019.

### ISSUE THREAD

**Issue by pboothe** [m-lab/mlab-ns-rate-limit#17]
Looks like we should redeploy after recompiling.

"A version of your app is using a deprecated version of Go. Please upgrade before October 1, 2019. [Learn more](https://cloud.google.com/appengine/docs/standard/go/go-differences?hl=en_US&_ga=2.244380544.-487813172.1544040740)"

https://console.cloud.google.com/appengine/services?organizationId=433637338589&project=mlab-ns

**Comment by stephen-soltesz** [comment]
Fixed by https://github.com/m-lab/mlab-ns-rate-limit/pull/19
