### ISSUE TITLE
STORY: Rate limit table.  Develop and deploy service in mlab-ns project(s) that generates table from BQ, populate datastore and memcache, including bloom filter.

### ISSUE THREAD

**Issue by gfr10598** [m-lab/mlab-ns-rate-limit#2]
We need to provide a table to mlab-ns with data about the high request rate clients.  There are perhaps 50K clients that make more than 6 requests per day.  (Our guideline is not more than 2 per hour, which is too generous).  For the high rate clients, we want mlab-ns to direct about 6 requests/day to our normal infrastructure, and any more than that should go to our alternate cloud VM infrastructure.

**Comment by pboothe** [comment]
Obsolete/done
